apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/nats
  - ../../../base/http
  - ../../../base/worker

patches:
  - target:
      kind: Deployment
      name: nats
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2